### ISSUE TITLE
Auto-Complete Ingredient Search

### ISSUE THREAD

**Issue by rickrizzo** [rickrizzo/GroGro#2]
This feature is _critical_ to the success of our application. When you type in an ingredient into the search field, autocomplete results from the USDA must show up to help standardize consumer data. A nice touch would be if pictures could also show up.

**Comment by PeterRyder** [comment]
This is an example of angular filtering which could help us

http://plnkr.co/edit/XklvXtc1AZpndjLvXrh8?p=preview
